package com.sps.product_microservice.configuration;

import org.modelmapper.ModelMapper;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;


import java.util.List;

@Configuration
public class Config {

    @Bean
    public ModelMapper modelMapper(){

//        ModelMapper modelMapper = new ModelMapper();

//        // Skip the Mapping between ID of ProductDTO to ID of Product cuz its autogenerated (SEQUENCE).
//        TypeMap<ProductDTO, Product> typeMap = modelMapper.createTypeMap(ProductDTO.class, Product.class);
//        typeMap.addMappings(mapper -> mapper.skip(Product::setId));

        return new ModelMapper();
    }

}
